import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readFile} from 'node:fs/promises';
import {createLeadAPI} from './leads-api.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const port=Number(process.env.MAISON_PORT||4190);
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2'};
const catalog=JSON.parse(await readFile(path.join(root,'data/catalog.json'),'utf8'));
const leadAPI=createLeadAPI({directory:process.env.MAISON_LEADS_DIR||path.join(root,'.maison-leads'),serviceIds:new Set(catalog.groups.flatMap(g=>g.services.map(s=>s.id)))});
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname==='/api/leads')return await leadAPI(req,res,url);if(url.pathname.startsWith('/api/booking/')){res.writeHead(410,{'Content-Type':'application/json'});res.end('{"error":"booking_moved_to_altegio"}');return;}const pathname=decodeURIComponent(url.pathname);if(!/^\/(?:$|index\.html$|maison-preview\.html$|styles\.css$|(?:app|motion|booking-model)\.js$|assets\/[\w.-]+$|data\/catalog\.js$)/.test(pathname)){res.writeHead(404);res.end('Not found');return;}const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));const data=await readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(data);}catch{res.writeHead(404);res.end('Not found');}}).listen(port,'127.0.0.1',()=>console.log(`Maison preview http://127.0.0.1:${port}/`));
